<?php
$this->registerCssFile('/templates/A62/css/style.css');
$this->registerCssFile('/templates/A62/css/responsive.css'); ?>

<body>
<header class="header">

</header>

<main class="main">
    <div class="landingpage-wrap">
        <div class="landing-maincontent-container">
            <section class="title">
                <h1 class="title__item">All about CV Services in Lagos</h1>
                <hr>
            </section>
        </div>
    </div>
    <div class="landingpage">
        <aside class="landingpage-right-sidebar">
            <div class="right-sidebar-container">
                <div class="right-sidebar-item">
                    <h4 class="right-sidebar-item__title">See here our samples for beautiful and suceessful CV templates</h4>
                    <div class="landing-images">
                        <img src="/templates/A62/img/cv1.png" alt="CV" class="landing-images__img1">
                        <img src="/templates/A62/img/cv2.png" alt="CV" class="landing-images__img2">
                        <img src="/templates/A62/img/cv3.png" alt="CV" class="landing-images__img3">
                    </div>
                    <p class="right-sidebar-item__question">Want to be successful?</p>
                    <button class="button-orange">CREATE YOUR CV</button>
                </div>
            </div>
        </aside>
        <div class="landingpage-maincontent">
            <div class="landing-maincontent-container">
                <section class="title">
                    <h1 class="title__item">All about CV Services in Lagos</h1>
                    <hr>
                    <p class="title__descr">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <img src="/templates/A62/img/lagos.png" alt="Lagos" class="title__img">
                    <p class="title__descr">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <p class="title__descr">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <button class="button-orange">CREATE YOUR CV</button>
                </section>
            </div>
        </div>
    </div>
</main>
<?php $this->registerJsFile('/templates/A62/js/app.js'); ?>
</body>