<?php /**
 * @var $user \app\models\UserProfile;
 */
$this->registerCssFile('/templates/A41/css/style.css');
$this->registerCssFile('/templates/A41/css/responsive.css'); ?>

<body>
<header class="header">

</header>

<main class="main">
    <div class="faq-tmpl">
        <div class="faq-container">
            <section class="title">
                <h1 class="title__item">faq</h1>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">How to get a job using DropCV?</h2>
                <p class="faq-question__descr">All you have to do is to:</p>
                <ul class="faq-question-list">
                    <li class="faq-question-list__item">Create an account on DropCV.</li>
                    <li class="faq-question-list__item">Create your CV.</li>
                    <li class="faq-question-list__item">Select from one of our beautiful CV templates</li>
                    <li class="faq-question-list__item">Download your CV in PDF format for offline sharing or copy and paste your CV link on social media (Twitter,Facebook,Linkedin,blogs,whatsapp and many other online platforms) e.g. i  am looking for a job, checkout my CV(paste your link).let employers and recruiters notice you with your CV link</li>
                    <li class="faq-question-list__item">Send your CV with cover letter as an application with our secured emailing system to employers and recruiters.</li>
                </ul>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">What can I get for free on DropCV?</h2>
                <p class="faq-question__descr">As a free user:</p>
                <ul class="faq-question-list">
                    <li class="faq-question-list__item">You can create an account on DropCV.</li>
                    <li class="faq-question-list__item">Create a CV and get a free CV template with a link for online sharing.</li>
                    <li class="faq-question-list__item">Download your CV in PDF format for offline sharing</li>
                </ul>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">What I need to do, to start using Premium Account?</h2>
                <p class="faq-question__descr">To use our Premium Account:</p>
                <ul class="faq-question-list">
                    <li class="faq-question-list__item">Select premium package</li>
                    <li class="faq-question-list__item">An invite form will be showed to you</li>
                    <li class="faq-question-list__item">Enter 3 of your friend’s name and emails</li>
                    <li class="faq-question-list__item">Click UNLOCK NOW</li>
                </ul>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">How to use the Professional Membership TO get a job faster?</h2>
                <ul class="faq-question-list">
                    <li class="faq-question-list__item">Subscribe to get our professional membership and get a pro badge on your CV</li>
                    <li class="faq-question-list__item">The PRO membership gives you access to professional CV templates</li>
                    <li class="faq-question-list__item">Employers and recruiters will notice you faster with our PRO badge on your CV</li>
                    <li class="faq-question-list__item">Send your professional CV as an application to employer s and recruiters through our secured emailing system.</li>
                    <li class="faq-question-list__item">Employers and recruiters will receive your professional CV with top priority.</li>
                </ul>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">Why it is good to invite my friends to DropCV?</h2>
                <p class="faq-question__descr">Inviting your friends to DropCV gives you the chance to enjoy our premium package and also allow your friends to use DropCV by giving them the opportunity to send and share their CV with employers and recruiters online or offline, your friends might be searching for their first job or changing their jobs. DropCV is a useful and hassle free solution for your friends in getting their dream jobs.</p>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">How I can support DropCV, to help build DropCV community?</h2>
                <p class="faq-question__descr">You can help DropCV build its community by inviting your friends to use DropCV, also you can help by educating and helping new users use DropCV in a positive way by creating video contents on Youtube, Vimeo and written content about DropCV on your blogs or on social media, you can also help by sharing the content you created on internet forums and blogs that way people know more about DropCV and its usefulness in simplifying the way people get jobs.</p>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">How can i share my CV online?</h2>
                <p class="faq-question__descr">You can share your CV online with the short link generated by our system, you will have to copy and paste your link on any online social and professional media with a call for action (an easy way to advertise your skills) share your CV link with friends and family on Whatsapp and on social media. You can also send your link as an email to recruiters and employers with a call for action. People clicking your link can view your CV and call you for interviews. Also, DropCV is a very useful tool for cold emailing when searching for jobs.</p>
            </section>
            <section class="faq-question">
                <h2 class="faq-question__title">How to share my CV offline</h2>
                <ul class="faq-question-list">
                    <li class="faq-question-list__item">Download your CV in PDF format.</li>
                    <li class="faq-question-list__item">Print your CV out and</li>
                    <li class="faq-question-list__item">Share offline with recruiters and employers.</li>
                </ul>
            </section>
            <section class="faq-good-luck">
                <h2 class="faq-good-luck__title">good luck!</h2>
                <div class="person-wrap">
                    <figure class="person-dropcv">
                        <img src="/templates/A41/img/Mirko.png" alt="person" class="person-dropcv__img circle">
                        <figcaption class="descr-wrap">
                            <p class="person-name">Mirko Riedel</p>
                            <p class="person-prof">Founder</p>
                        </figcaption>
                    </figure>
                    <figure class="person-dropcv">
                        <img src="/templates/A41/img/Caleb.png" alt="person" class="person-dropcv__img circle">
                        <figcaption class="descr-wrap">
                            <p class="person-name">Caleb Adefala</p>
                            <p class="person-prof">Founder</p>
                        </figcaption>
                    </figure>
                </div>
            </section>
            <hr>
            <section class="contact-us">
                <h2 class="contact-us__title">DIDN’T FIND WHAT YOU WERE LOOKING FOR? CONTACT US!</h2>
                <button class="button-orange">contact</button>
            </section>
        </div>
    </div>
</main>
</body>
<?php $this->registerJsFile('/templates/A41/js/app.js'); ?>